### ISSUE TITLE
ANALOG_WIDE mode causes issues in some games

### ISSUE THREAD

**Issue by vladone97** [Rinnegatamante/AnalogsEnhancer#2]
ANALOG_WIDE stretches the analog values over a wider area, thus giving better precision in some games. However, due to the values being stretched over a wider area, the analogs can't reach maximum or minimum values on both axes at the same time. This leads to issues in other games. For example, in Sword Art Online: Lost Song, I can't run or sprint diagonally with AnalogsEnhancer active. There should be a version of the plugin that doesn't force ANALOG_WIDE mode onto games and apps that normally use ANALOG mode.

**Comment by Rinnegatamante** [comment]
I'll add a new config voice to disable the ANALOG_WIDE patch.

**Comment by Rinnegatamante** [comment]
[AnalogsEnhancer.zip](https://github.com/Rinnegatamante/AnalogsEnhancer/files/3891152/AnalogsEnhancer.zip)

Here it is, check if it works with this version. Config file has a new value. New config looks like this:

left=VALUE,y/n;right=VALUE,y/n;y/n

the last y will enable ANALOG_WIDE patch. Setting it to n will disable it.

**Comment by vladone97** [comment]
Yep, I tested it in-game and with Vita Hardware Test and the new setting works as intended. Thanks for the update.
On a completely unrelated note, in Vita Hardware Test, the analog values only go up to 254 rather than the usual 255 when software rescaling is enabled. Not sure if this was also the case in the previous version though.
